CI: Test if we can build puppetboard
In our normal test pipeline, we didn't verify if we can properly build
the package. because of that, the last 6.0.0 release failed:

```
Run python setup.py build sdist bdist_wheel
Traceback (most recent call last):
  File "/home/runner/work/puppetboard/puppetboard/setup.py", line 3, in <module>
    from setuptools.command.test import test as TestCommand
ModuleNotFoundError: No module named 'setuptools'
```